name: Release
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install the dependencies
        run: npm ci
      - name: Initialize Git user
        run: |
          git config --global user.email "patouillardfranck3@gmail.com"
          git config --global user.name "Freddyede"
      - name: Initialize the NPM config
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run release

        run: npm run release --ci
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}